"""Audit module catalog seed — 22 modules (Milestone 5)."""

from __future__ import annotations

MODULE_CATALOG_SEED: list[dict] = [
    {
        "code": "JOURNAL_ENTRY_TESTING",
        "name": "Journal Entry Testing",
        "description": "AI-assisted analysis of journal entries for anomalies, unusual patterns, and manual adjustments requiring review.",
        "category": "General Ledger",
        "slug": "journal-entry-testing",
        "icon": "BookOpen",
        "implementation_status": "built",
        "display_order": 1,
    },
    {
        "code": "REVENUE_TESTING",
        "name": "Revenue Testing",
        "description": "AI-assisted revenue substantive testing — sales register upload, cutoff analysis, GST checks, and exception reporting.",
        "category": "Revenue",
        "slug": "revenue-testing",
        "icon": "Receipt",
        "implementation_status": "built",
        "display_order": 2,
    },
    {
        "code": "PROCUREMENT_TESTING",
        "name": "Procurement Testing",
        "description": "AI-assisted procurement controls testing — vendor invoice upload, PO matching, duplicate payment detection, and findings.",
        "category": "Procurement",
        "slug": "procurement-testing",
        "icon": "ShoppingCart",
        "implementation_status": "built",
        "display_order": 3,
    },
    {
        "code": "LEDGER_SCRUTINY",
        "name": "Ledger Scrutiny",
        "description": "Automated scrutiny of general ledger accounts with variance analysis, trend detection, and account-level risk scoring.",
        "category": "General Ledger",
        "slug": "ledger-scrutiny",
        "icon": "FileSpreadsheet",
        "implementation_status": "planned",
        "display_order": 4,
    },
    {
        "code": "DUPLICATE_PAYMENT",
        "name": "Duplicate Payment Checking",
        "description": "Detect duplicate vendor payments, repeated invoice references, and overlapping disbursements across transactions.",
        "category": "Accounts Payable",
        "slug": "duplicate-payment-checking",
        "icon": "Copy",
        "implementation_status": "planned",
        "display_order": 5,
    },
    {
        "code": "BANK_RECONCILIATION",
        "name": "Bank Reconciliation",
        "description": "Match bank statements with book records using AI-powered reconciliation and exception highlighting.",
        "category": "Cash & Bank",
        "slug": "bank-reconciliation",
        "icon": "Landmark",
        "implementation_status": "planned",
        "display_order": 6,
    },
    {
        "code": "GST_MISMATCH",
        "name": "GST Mismatch Checking",
        "description": "Identify GST return discrepancies between books, invoices, and filed returns with automated variance reports.",
        "category": "Indirect Tax",
        "slug": "gst-mismatch-checking",
        "icon": "Scale",
        "implementation_status": "planned",
        "display_order": 7,
    },
    {
        "code": "PO_MATCHING",
        "name": "Purchase Order Matching",
        "description": "Three-way match between purchase orders, goods receipt notes, and vendor invoices for procurement controls.",
        "category": "Procurement",
        "slug": "purchase-order-matching",
        "icon": "ClipboardCheck",
        "implementation_status": "planned",
        "display_order": 8,
    },
    {
        "code": "VENDOR_INVOICE",
        "name": "Vendor Invoice Validation",
        "description": "Validate vendor invoices against contracts, tax rules, approval limits, and master data integrity.",
        "category": "Accounts Payable",
        "slug": "vendor-invoice-validation",
        "icon": "Receipt",
        "implementation_status": "planned",
        "display_order": 9,
    },
    {
        "code": "EXPENSE_CLAIM",
        "name": "Expense Claim Verification",
        "description": "Review employee expense claims for policy compliance, duplicate submissions, and supporting documentation.",
        "category": "Expenses",
        "slug": "expense-claim-verification",
        "icon": "Wallet",
        "implementation_status": "planned",
        "display_order": 10,
    },
    {
        "code": "FIXED_ASSET",
        "name": "Fixed Asset Verification",
        "description": "Reconcile fixed asset registers with physical verification records and capitalization policies.",
        "category": "Fixed Assets",
        "slug": "fixed-asset-verification",
        "icon": "Building2",
        "implementation_status": "planned",
        "display_order": 11,
    },
    {
        "code": "DEPRECIATION",
        "name": "Depreciation Recalculation",
        "description": "Recalculate depreciation under applicable accounting standards and flag variances from recorded amounts.",
        "category": "Fixed Assets",
        "slug": "depreciation-recalculation",
        "icon": "Calculator",
        "implementation_status": "planned",
        "display_order": 12,
    },
    {
        "code": "TDS_CHECKING",
        "name": "TDS Deduction Checking",
        "description": "Verify TDS deductions, applicable rates, and challan remittances against statutory requirements.",
        "category": "Direct Tax",
        "slug": "tds-deduction-checking",
        "icon": "Banknote",
        "implementation_status": "planned",
        "display_order": 13,
    },
    {
        "code": "GST_ITC",
        "name": "GST Input Tax Credit Validation",
        "description": "Validate ITC eligibility, invoice matching, and reversal requirements under GST regulations.",
        "category": "Indirect Tax",
        "slug": "gst-itc-validation",
        "icon": "FileCheck2",
        "implementation_status": "planned",
        "display_order": 14,
    },
    {
        "code": "CUSTOMER_BALANCE",
        "name": "Customer Balance Confirmation Tracking",
        "description": "Track customer balance confirmation requests, responses, and follow-ups for receivables audit procedures.",
        "category": "Accounts Receivable",
        "slug": "customer-balance-confirmation",
        "icon": "Users",
        "implementation_status": "planned",
        "display_order": 15,
    },
    {
        "code": "PAYROLL",
        "name": "Payroll Audit Checking",
        "description": "Audit payroll computations, statutory deductions, and headcount reconciliations for accuracy and compliance.",
        "category": "Payroll",
        "slug": "payroll-audit-checking",
        "icon": "UserCheck",
        "implementation_status": "planned",
        "display_order": 16,
    },
    {
        "code": "USER_ACCESS",
        "name": "User Access Review",
        "description": "Review user access rights and privileged accounts for IT general controls and regulatory compliance.",
        "category": "IT Controls",
        "slug": "user-access-review",
        "icon": "Lock",
        "implementation_status": "planned",
        "display_order": 17,
    },
    {
        "code": "SOD",
        "name": "Segregation of Duties Checking",
        "description": "Identify conflicts in user roles and incompatible duty assignments across ERP and financial systems.",
        "category": "IT Controls",
        "slug": "segregation-of-duties",
        "icon": "ShieldCheck",
        "implementation_status": "planned",
        "display_order": 18,
    },
    {
        "code": "COMPLIANCE",
        "name": "Compliance Checklist Verification",
        "description": "Verify completion of regulatory, engagement, and firm compliance checklists with audit trail tracking.",
        "category": "Compliance",
        "slug": "compliance-checklist",
        "icon": "ClipboardCheck",
        "implementation_status": "planned",
        "display_order": 19,
    },
    {
        "code": "DOC_MATCHING",
        "name": "Supporting Document Matching",
        "description": "Match transactions with supporting vouchers, invoices, approvals, and underlying documentation.",
        "category": "Documentation",
        "slug": "supporting-document-matching",
        "icon": "FileSearch",
        "implementation_status": "planned",
        "display_order": 20,
    },
    {
        "code": "EXCEPTION_REPORT",
        "name": "Exception Report Preparation",
        "description": "Auto-generate exception reports from audit test results, findings, and unresolved review items.",
        "category": "Reporting",
        "slug": "exception-report-preparation",
        "icon": "AlertTriangle",
        "implementation_status": "planned",
        "display_order": 21,
    },
    {
        "code": "INVOICE_CHECKING",
        "name": "Invoice Checking",
        "description": "Validate sales and purchase invoices for arithmetic accuracy, tax computation, and completeness.",
        "category": "Revenue & AP",
        "slug": "invoice-checking",
        "icon": "Receipt",
        "implementation_status": "planned",
        "display_order": 22,
    },
]

IMPLEMENTATION_STATUSES = frozenset({"built", "beta", "planned"})

PROJECT_TYPE_TO_MODULE_CODE = {
    "journal_testing": "JOURNAL_ENTRY_TESTING",
    "revenue_testing": "REVENUE_TESTING",
    "procurement_testing": "PROCUREMENT_TESTING",
}

MODULE_CODE_TO_PROJECT_TYPE: dict[str, str] = {
    module_code: project_type
    for project_type, module_code in PROJECT_TYPE_TO_MODULE_CODE.items()
}

MODULE_CODE_TO_NAME: dict[str, str] = {
    entry["code"]: entry["name"] for entry in MODULE_CATALOG_SEED
}

PROJECT_TYPE_TO_MODULE_NAME: dict[str, str] = {
    project_type: MODULE_CODE_TO_NAME[module_code]
    for project_type, module_code in PROJECT_TYPE_TO_MODULE_CODE.items()
}
